/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAnalystRouteImport } from './routes/ai-analyst'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as LeadershipUpdateRouteImport } from './routes/leadership-update'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/_diag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalystRoute = AiAnalystRouteImport.update({
  id: '/ai-analyst',
  path: '/ai-analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipUpdateRoute = LeadershipUpdateRouteImport.update({
  id: '/leadership-update',
  path: '/leadership-update',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/_diag',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/data-sources': typeof DataSourcesRoute
  '/leadership-update': typeof LeadershipUpdateRoute
  '/pipeline': typeof PipelineRoute
  '/work-orders': typeof WorkOrdersRoute
  '/api/public': typeof ApiPublicDiagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/data-sources': typeof DataSourcesRoute
  '/leadership-update': typeof LeadershipUpdateRoute
  '/pipeline': typeof PipelineRoute
  '/work-orders': typeof WorkOrdersRoute
  '/api/public': typeof ApiPublicDiagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/data-sources': typeof DataSourcesRoute
  '/leadership-update': typeof LeadershipUpdateRoute
  '/pipeline': typeof PipelineRoute
  '/work-orders': typeof WorkOrdersRoute
  '/api/public/_diag': typeof ApiPublicDiagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analyst'
    | '/data-sources'
    | '/leadership-update'
    | '/pipeline'
    | '/work-orders'
    | '/api/public'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analyst'
    | '/data-sources'
    | '/leadership-update'
    | '/pipeline'
    | '/work-orders'
    | '/api/public'
  id:
    | '__root__'
    | '/'
    | '/ai-analyst'
    | '/data-sources'
    | '/leadership-update'
    | '/pipeline'
    | '/work-orders'
    | '/api/public/_diag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalystRoute: typeof AiAnalystRoute
  DataSourcesRoute: typeof DataSourcesRoute
  LeadershipUpdateRoute: typeof LeadershipUpdateRoute
  PipelineRoute: typeof PipelineRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analyst': {
      id: '/ai-analyst'
      path: '/ai-analyst'
      fullPath: '/ai-analyst'
      preLoaderRoute: typeof AiAnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-update': {
      id: '/leadership-update'
      path: '/leadership-update'
      fullPath: '/leadership-update'
      preLoaderRoute: typeof LeadershipUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/_diag': {
      id: '/api/public/_diag'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalystRoute: AiAnalystRoute,
  DataSourcesRoute: DataSourcesRoute,
  LeadershipUpdateRoute: LeadershipUpdateRoute,
  PipelineRoute: PipelineRoute,
  WorkOrdersRoute: WorkOrdersRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
